### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by joanqcflow** [dtelad11/cytutils#13]
Hello, 

I can't install cytutils, I have this error on Rstudio : 

> remotes::install_github("ismmshimc/cytutils")
Downloading GitHub repo ismmshimc/cytutils@HEAD
√  checking for file 'C:\Users\joand\AppData\Local\Temp\Rtmp8WqrBF\remotes2b6456ee5734\ismms-himc-cytutils-53ec353/DESCRIPTION' ...
-  preparing 'cytutils':
√  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
-  building 'cytutils_0.1.0.tar.gz'
   
Installation du package dans ‘C:/Users/joand/OneDrive/Documents/R/win-library/4.1’
(car ‘lib’ n'est pas spécifié)
* installing *source* package 'cytutils' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Erreur dans loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  aucun package nommé 'flowCore' n'est trouvé
Appels : <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Exécution arrêtée
ERROR: lazy loading failed for package 'cytutils'
* removing 'C:/Users/joand/OneDrive/Documents/R/win-library/4.1/cytutils'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/joand/AppData/Local/Temp/Rtmp8WqrBF/file2b6444117a1/cytutils_0.1.0.tar.gz’ had non-zero exit status

What can I do to solve that please ? is it a version issue ? 

Thanks for your help, 

Joan

**Comment by dtelad11** [comment]
Could you please try doing the following?

install.packages("BiocManager")
BiocManager::install("flowCore")

And see if that works?

**Comment by joanqcflow** [comment]
it worked ! thank you very much ! Best, Joan

**Comment by dtelad11** [comment]
That's great ^.^ thanks for letting me know.
