### ISSUE TITLE
Reduced file size

### ISSUE THREAD

**Issue by damali3** [dtelad11/cytutils#15]
Hi,

I used the package to rename the channels in the FCS files and it worked great. However, I noticed that the size of the file was drastically reduced (around 3 times), so I was wondering if there is an explanation for it and if there is any data/precision loss.

Thanks!

**Comment by dtelad11** [comment]
https://cytoforum.stanford.edu/viewtopic.php?f=3&t=1607

FCS files that come from the CyTOF have an additional section that is used by the Fluidigm software for normalization. Personally, I fondly refer to it as the "super-secret-Fluidigm-section". If you manipulate the file outside of the Fluidigm software (via FlowJo, Cytobank, R, etc.) that section will be discarded, cutting the file size by half.

**Comment by damali3** [comment]
Thank you, now it's clear!
